articles/urls.py
from django.http import JsonResponse
from django.urls import path
from . import views

app_name = 'articles'

def data1(request):
    data = {
        "name": "1",
        "level": 10,
        "url":"https://www.koreaminecraft.net/files/attach/images/21283/212/699/11167c822299f03f6f86ffd1ff4f5e3c.png",
        "item": ["검", "방패" ]
    }
    return JsonResponse(data)

def data2(request):
    data = {
        "name": "2",
        "level": 20,
        "url":"https://pixelart.pe.kr/data/editor/2109/afda73261b1d6e9b9d975acb9cedf366_1631624938_7116.png",
        "item": ["창", "검"]
    }
    return JsonResponse(data)

urlpatterns = [
    path('', views.index, name='index'),

    # Rest
    path('data1',data1),
    path('data2',data2),
    path('page',views.get_page),


    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment, name='comment'),
    path('<int:article_pk>/upcount', views.upcount, name='upcount'),
    path('search/', views.search, name='search'),
    path('pointshop/', views.pointshop, name='pointshop'),
    path('<int:icon_id>/<int:icon_price>/buy/', views.icon_buy, name='icon_buy'),
    path('profile/', views.profile, name='profile'),
    path('<int:icon_id>/icon_setting/', views.icon_setting, name='icon_setting'),
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:color_name>/<int:color_price>/buy/', views.color_buy, name='color_buy'),
    path('<str:color_name>/color_setting/username', views.color_username, name='color_username'),
    path('<str:color_name>/color_setting/title', views.color_title, name='color_title'),



    

    path('download/', views.download, name='download'),
    path('test/', views.test, name='test'),
    

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movies, name='movies'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>', views.detail, name='detail'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.connect),
    path('test/', views.test),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    genre_choices = (
	('기타', '기타'),
    ('액션', '액션'),
    ('공포', '공포'),
    ('로맨스', '로맨스'),
    ('스릴러', '스릴러'),
    )
    genre = models.CharField(max_length=10, choices=genre_choices, default='기타')
    username = models.CharField(default='익명',max_length=16)
    title = models.CharField(max_length=20)
    score = models.FloatField()
    content = models.TextField()
    release_date = models.DateField(auto_now=False)
    count = models.IntegerField(default=0)
    poster_url = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from movies.models import Movie


class MovieForm(forms.ModelForm):
    # header = forms.CharField(
    #     label='장르',
    #     widget=forms.Select(
    #         attrs={
    #             'choices': 'header_choices'
    #         }
    #     )
    # )
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'titlebox',
                'placeholder': ' 제목을 입력바람!'
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '간략한 영화내용!'
            }
        )
    )
    score = forms.FloatField(
        label='평점',
        widget=forms.NumberInput(
            attrs={
                'type': 'number',
                'min': '0',
                'max': '5',
                'step': '0.5',
            }
        )
    )
    release_date = forms.DateField(
        label='출시일',
        widget=forms.DateInput(
            attrs={
                'type': 'date',
            }
        )
    )
    poster_url = forms.CharField(
        label='영화포스터',
        widget=forms.TextInput(
            attrs={
                'type': 'url',
                'placeholder': '영화 이미지주소를 입력'
                
            }
        )

    )

    class Meta:
        model = Movie
        fields = ('genre', 'title', 'score', 'content', 'release_date', 'poster_url')

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def movies(request):
    movies = Movie.objects.all()

    context = {
        'movies': movies,
    }
    return render(request, 'movies/movies.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:movies')

    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)

    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)

def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.user.is_authenticated:
        if request.method == 'POST':
            movie.delete()
            return redirect('movies:movies')

    return redirect('movies:detail', movie.pk)

        

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>MovieCreate</h1>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="등록">
  </form>

  <a href="{% url 'movies:movies' %}">
    <button>뒤로가기</button>
  </a>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ movie.title }}</h1>
  <hr>
  <div class="posterbox"><img src="{{ movie.poster_url }}" class="img-size" alt="{{ movie.pk }}"></div>
  <section class="poorstory">
    <div class="justify-end">
      <p>조회수:
        {{ movie.count }}</p>
    </div>
    <hr>
    {{ movie.content }}
    <hr>

    <a href="{% url 'movies:movies' %}">
      <button>뒤로가기</button>
    </a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
      {% csrf_token %}
      <button>삭제</button>
    </form>

  {% endblock content %}

movies/templates/movies/movies.html
{% extends 'base.html' %}

{% block content %}
  <h1>MovieCreate</h1>
  <div class="display-flex-center">
    <div class="display-flex">
      {% for movie in movies reversed %}
        <div class="posterbox">
          <div class="posterbox2">
            <div class="imgbox">
              <a href="{% url 'movies:detail' movie.pk %}">
                <img src="{{ movie.poster_url }}" class="img-size" alt="{{ movie.pk }}"></a>
            </div>
            <div>
              <div class="movie-titlebox cutefont2">제목:
                {{ movie.title }}</div>
              <div class="poorstory2">
                <div>
                  <p style=" margin: 0%;">평점:
                    <span style="color: red;">{{ movie.score }}</span></p>
                  <p style=" margin: 0%;">장르:
                    {{ movie.genre }}</p>
                </div>
                <p class="movie-releasebox">출시:
                  {{ movie.release_date|date:"Y.m.d" }}</p>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <form action="{% url 'movies:create' %}">
    <input class="poorstory2" type="submit" value="영화등록">
  </form>

  <a href="{% url 'articles:index' %}">
    <button>뒤로가기</button>
  </a>

{% endblock content %}