articles/urls.py
from django.http import JsonResponse
from django.urls import path
from . import views

app_name = 'articles'

def data1(request):
    data = {
        "name": "1",
        "level": 10,
        "url":"https://www.koreaminecraft.net/files/attach/images/21283/212/699/11167c822299f03f6f86ffd1ff4f5e3c.png",
        "item": ["검", "방패" ]
    }
    return JsonResponse(data)

def data2(request):
    data = {
        "name": "2",
        "level": 20,
        "url":"https://pixelart.pe.kr/data/editor/2109/afda73261b1d6e9b9d975acb9cedf366_1631624938_7116.png",
        "item": ["창", "검"]
    }
    return JsonResponse(data)

urlpatterns = [
    path('', views.index, name='index'),

    # Rest
    path('data1',data1),
    path('data2',data2),
    path('page',views.get_page),


    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment, name='comment'),
    path('<int:article_pk>/upcount', views.upcount, name='upcount'),
    path('search/', views.search, name='search'),
    path('pointshop/', views.pointshop, name='pointshop'),
    path('<int:icon_id>/<int:icon_price>/buy/', views.icon_buy, name='icon_buy'),
    path('profile/', views.profile, name='profile'),
    path('<int:icon_id>/icon_setting/', views.icon_setting, name='icon_setting'),
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:color_name>/<int:color_price>/buy/', views.color_buy, name='color_buy'),
    path('<str:color_name>/color_setting/username', views.color_username, name='color_username'),
    path('<str:color_name>/color_setting/title', views.color_title, name='color_title'),



    

    path('download/', views.download, name='download'),
    path('test/', views.test, name='test'),
    

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movies, name='movies'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>', views.detail, name='detail'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.connect),
    path('test/', views.test),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    header_choices = (
	('기타', '기타'),
    ('잡담', '잡담'),
    ('유머', '유머'),
    ('게임', '게임'),
    ('일상', '일상'),
    )
    header = models.CharField(max_length=2, choices=header_choices, default='기타')
    username = models.CharField(default='익명',max_length=50)
    title = models.CharField(max_length=30)
    content = models.TextField()
    count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def 날짜이쁘게(self,date):
        return date.strftime("%Y/%m/%d/ %H:%M:%S")
    
    def 욕필터(self,str):
        return str.replace("씨팔","**")


class Comment(models.Model):
    username = models.CharField(default='익명',max_length=50)
    article_id = models.IntegerField(default=0)
    content = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

class Upcheck(models.Model):
    username = models.CharField(default='익명',max_length=50)
    article_id = models.IntegerField(default=0)


class Usericon(models.Model):
    icon_id = models.IntegerField()
    iconname = models.CharField(max_length=20)
    url = models.TextField()
    price = models.IntegerField(default=500)

class Profile(models.Model):
    username = models.CharField(max_length=50)
    icon_id = models.IntegerField(default=0)
    icon_url = models.TextField(default='icon/gunbbang.png')
    id_color = models.TextField(default='black')
    title_color = models.TextField(default='black')

class Itembox(models.Model):
    username = models.CharField(max_length=50)
    icon_id = models.IntegerField(default=0)
    
class Colorbox(models.Model):
    username = models.CharField(max_length=50)
    color =  models.TextField(default='black')

articles/forms.py
from django import forms
from articles.models import Article

# class ArticleForm(forms.Form):
    # title = forms.CharField(max_length=10)
    # content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='Title',
        widget=forms.TextInput(
            attrs={
                'class': 'titlebox',
                'placeholder': '  제목을 입력바람!'
            }
        )
    )
    content = forms.CharField(
        label='Content',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 입력바람!'
            }
        )
    )

    class Meta:
        model = Article
        fields = ('header', 'title', 'content',)

articles/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.core import serializers
from django.contrib.auth.decorators import login_required
from accounts.models import User
from .forms import ArticleForm
from .models import Article, Comment, Itembox, Upcheck, Usericon, Colorbox
from .context_processors import Profile
from datetime import datetime 
import time
interval = 1

def get_page(request):
    global interval
    page = int(request.GET.get('page', 1))                      # 요청 페이지를 받아올때 인트값으로, 디폴트 1
    page_size = 10                                              # 보여줄 페이지의 개수
    page_end = page * page_size                                 # 아래에서 게시글을 페이지개수만큼 자를 변수
    page_start = page_end - page_size
    paginations = (len(Article.objects.all()) // page_size) +1  # 모든 게시글개수를 페이지 사이즈만큼 나누고 +1 만큼 페이지네이션 생성 
    paginations_size = 3                                        # 페이지네이션 사이즈 (html에도 값 바꿔주어야함)
    if page <= paginations_size:                                # 페이지네이션 사이즈 처리 구간 첫 1,2,3 구간일때
        interval = 1                                            
    if page != 1 and page % paginations_size == 1:              # 페이지가 1이아니고 페이지네이션 사이즈로 나눈 나머지 1일때 (즉 현재설정으론 4페이지)
        interval = page                                         # 글로벌 interval을 page값으로 할당 (아래에 range범위 바꿔서 다시 렌더링 해야함)
    # print('&&$$$$$$$$$$$$$$$$',paginations)
    articles = Article.objects.all()[::-1]
    articles = articles[page_start:page_end]                    # 현재 페이지 사이즈 10개만큼 잘라서 렌더링해야함

    time_now = int(time.mktime(datetime.now().date().timetuple()))      # 중요!! 현재시간의 현재날짜 00시 기준의 값을 타임스탬프로 받아와야함!

    for article in articles:
        # article.test = article.날짜이쁘게(article.created_at)
        article.title = article.욕필터(article.title)
        article_time = int(time.mktime(article.created_at.timetuple()))     # 게시글 작성시간을 타임스탬프화 시키고
        article.time_slice = article_time - time_now + 32400                # 중요!! 오늘날짜 00시 기준값에서 작성시간 빼고 32400(시차)만큼 더해준값 음수면 넘어가게..(이 값으로 index페이지에서 사용)
        # print('@@@@@@', article.time_slice)                                                                        

        if article.comment_count == 0:
            article.comment_count = ''          # 코멘트 0 이면 빈칸 
        else:
             article.comment_count = f' [{ article.comment_count }]'    
    
    # articles for문돌면서 거기에 profile꽂아주려함
    # 그럼 기존 html쪽 for문에서 article.profile.icon_url하믄대니까
    # print('aa',usernames)


    # 인기글 정렬하는거 order_by를 통해 정렬 '-'을 통해 많은순
    article_popular = Article.objects.all().order_by('-up_count')[:3]  

    for popular in article_popular:
        popular.title = popular.욕필터(popular.title)
        popular_time = int(time.mktime(popular.created_at.timetuple()))    
        popular.time_slice = popular_time - time_now + 32400     
        if popular.comment_count == 0:
            popular.comment_count = ''
        else:
             popular.comment_count = f' [{ popular.comment_count}]'

    #lambda쓰는거조금씩이제 해보자!!
    usernames = list(map(lambda x:x.username, articles))
    usernames2 = list(map(lambda x:x.username, article_popular))
    # print('@@@',usernames)
    # print('@@@',usernames2)
    # 여기서 usernames로 profile끌어오면 profiles들어잇고
    profiles = Profile.objects.filter(username__in=usernames)
    profiles2 = Profile.objects.filter(username__in=usernames2)
    

    for article in articles:
        # profiles이거안에 article.username이랑 profiles중의 profile.username이같은거 무족권있을꺼고
        # 그걸 article.profile = profile 해서넣어준다는뜻 데이터베이스에 지정한 필드값들만 이렇게 끌고올수있는게 아니다!
        for profile in profiles:
            if profile.username == article.username :
                article.profile = profile.icon_url
                article.id_color = profile.id_color
                article.title_color = profile.title_color

    for article in article_popular:                 
        for pro in profiles2:
            if pro.username == article.username :
                article.profile = pro.icon_url
                article.id_color = pro.id_color
                article.title_color = pro.title_color

    context ={
        'articles': articles,
        'article_popular': article_popular,
        'range': range(interval, paginations + 1),                      # 여기 range를 전달함으로써 구간만큼 페이지네이션 버튼 생성
        'interval': interval,
        'interval_2': interval + paginations_size,
        'paginations_size': paginations_size,
    }
    context = serializers.serialize("json", articles)
    return HttpResponse(context, content_type='application/json')
    #return JsonResponse(context,safe=False)

# Create your views here.
def index(request):
    global interval
    page = int(request.GET.get('page', 1))                      # 요청 페이지를 받아올때 인트값으로, 디폴트 1
    page_size = 10                                              # 보여줄 페이지의 개수
    page_end = page * page_size                                 # 아래에서 게시글을 페이지개수만큼 자를 변수
    page_start = page_end - page_size
    paginations = (len(Article.objects.all()) // page_size) +1  # 모든 게시글개수를 페이지 사이즈만큼 나누고 +1 만큼 페이지네이션 생성 
    paginations_size = 3                                        # 페이지네이션 사이즈 (html에도 값 바꿔주어야함)
    if page <= paginations_size:                                # 페이지네이션 사이즈 처리 구간 첫 1,2,3 구간일때
        interval = 1                                            
    if page != 1 and page % paginations_size == 1:              # 페이지가 1이아니고 페이지네이션 사이즈로 나눈 나머지 1일때 (즉 현재설정으론 4페이지)
        interval = page                                         # 글로벌 interval을 page값으로 할당 (아래에 range범위 바꿔서 다시 렌더링 해야함)
    # print('&&$$$$$$$$$$$$$$$$',paginations)
    articles = Article.objects.all()[::-1]
    articles = articles[page_start:page_end]                    # 현재 페이지 사이즈 10개만큼 잘라서 렌더링해야함

    time_now = int(time.mktime(datetime.now().date().timetuple()))      # 중요!! 현재시간의 현재날짜 00시 기준의 값을 타임스탬프로 받아와야함!

    for article in articles:
        # article.test = article.날짜이쁘게(article.created_at)
        article.title = article.욕필터(article.title)
        article_time = int(time.mktime(article.created_at.timetuple()))     # 게시글 작성시간을 타임스탬프화 시키고
        article.time_slice = article_time - time_now + 32400                # 중요!! 오늘날짜 00시 기준값에서 작성시간 빼고 32400(시차)만큼 더해준값 음수면 넘어가게..(이 값으로 index페이지에서 사용)
        # print('@@@@@@', article.time_slice)                                                                        

        if article.comment_count == 0:
            article.comment_count = ''          # 코멘트 0 이면 빈칸 
        else:
             article.comment_count = f' [{ article.comment_count }]'    
    
    # articles for문돌면서 거기에 profile꽂아주려함
    # 그럼 기존 html쪽 for문에서 article.profile.icon_url하믄대니까
    # print('aa',usernames)


    # 인기글 정렬하는거 order_by를 통해 정렬 '-'을 통해 많은순
    article_popular = Article.objects.all().order_by('-up_count')[:3]  

    for popular in article_popular:
        popular.title = popular.욕필터(popular.title)
        popular_time = int(time.mktime(popular.created_at.timetuple()))    
        popular.time_slice = popular_time - time_now + 32400     
        if popular.comment_count == 0:
            popular.comment_count = ''
        else:
             popular.comment_count = f' [{ popular.comment_count}]'

    #lambda쓰는거조금씩이제 해보자!!
    usernames = list(map(lambda x:x.username, articles))
    usernames2 = list(map(lambda x:x.username, article_popular))
    # print('@@@',usernames)
    # print('@@@',usernames2)
    # 여기서 usernames로 profile끌어오면 profiles들어잇고
    profiles = Profile.objects.filter(username__in=usernames)
    profiles2 = Profile.objects.filter(username__in=usernames2)
    

    for article in articles:
        # profiles이거안에 article.username이랑 profiles중의 profile.username이같은거 무족권있을꺼고
        # 그걸 article.profile = profile 해서넣어준다는뜻 데이터베이스에 지정한 필드값들만 이렇게 끌고올수있는게 아니다!
        for profile in profiles:
            if profile.username == article.username :
                article.profile = profile.icon_url
                article.id_color = profile.id_color
                article.title_color = profile.title_color

    for article in article_popular:                 
        for pro in profiles2:
            if pro.username == article.username :
                article.profile = pro.icon_url
                article.id_color = pro.id_color
                article.title_color = pro.title_color

    context ={
        'articles': articles,
        'article_popular': article_popular,
        'range': range(interval, paginations + 1),                      # 여기 range를 전달함으로써 구간만큼 페이지네이션 버튼 생성
        'interval': interval,
        'interval_2': interval + paginations_size,
        'paginations_size': paginations_size,
    }
    
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save() # save()는 데이터에 저장도하는데 위에서 지정안하면 새로 객체도 만듬
            article.username = request.user.username    # 따로해주는 이유는 지금 article.username은 디폴트값이 익명으로 되어있다
            article.save()
            request.user.point += 300
            request.user.save()

            return redirect('articles:detail', article.pk)
    
    else:
        # NEW 처리하는곳 GET으로 요청들어왔을때임
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context) # 이러면 기존 작성한 내용도 그대로보존

@login_required
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    profi = Profile.objects.get(username=article.username)
    #기존
    #article.username = request.user
    # => 객체임
    article.count += 1
    article.save()
    if article.username != '익명':
        article_user = User.objects.get(username=article.username)
        article.point = article_user.point

    comments = Comment.objects.filter(article_id=article_pk)
    usernames = list(map(lambda x:x.username, comments))
    # print('@@@',usernames)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="생썽">
  </form>

  <a href="{% url 'articles:index' %}">
    <button>뒤로가기</button>
  </a>
  

{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <hr>
  <section class="poorstory">
    <header class="header-all">
      <div class="header-titlebox">
        <div class="header-group">[{{ article.header }}]</div>
        <div>{{ article.title }}</div>
      </div>
      <div class="header-box">
        <div class="header-imagebox">
          <img style="width: 100px; height: 100px; margin-right: 5px;" src="{% static profi.icon_url %}" alt="icon"/>
        </div>
        <div>
          <div class="header-namebox">
            <div>{{ article.username }}</div>
          </div>
          <div class="header-viewbox">
            <div>포인트:
              {{ article.point }}</div>
            <div>조회:
              {{ article.count }}</div>
            <div>
              작성:
              {{ article.created_at|date:"y-m-d (H:i)" }}</div>
          </div>
        </div>
      </div>
    </header>

    <div class="textarea-content">
      {{ article.content }}</div>

    <div class="justify-center">
      <button class="upbox" type="button" data-bs-toggle="modal" data-bs-target="#upcheck">
        <div>{{ article.up_count }}</div><img style="width: 30px;" src="{% static 'img/up.jpg' %}" alt="">
      </button>
    </div>
  </section>
  <hr>
  <footer class="poorstory">
    <div style="border-bottom: solid 1px burlywood;">
      {% for comment in comments %}
        <div class="justify-start comment-border">
          <div class="justify-start comment-box">
            <img style="width: 20px; height: 20px; margin-right: 5px;" src="{% static comment.profile %}" alt="icon"/>
            <span style="color: {{ comment.name_color }};">{{ comment.username }}</span>
          </div>
          <div class="comment-box2">
            <div style="color: {{ comment.title_color }};">{{ comment.content }}</div>
            <div class="d-flex align-items-center">
              <div class="comment-date">{{ comment.created_at }}</div>
              <div>
                <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
                  {% csrf_token %}
                  <button style="padding: 0px; width: 15px; height: 15px; border: none; margin-right: 5px;" type="submit">
                    <img style="width: 100%; height: 100%;" src="{% static 'img/x.png' %}" alt="xbutton"/>
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    <hr>
    <form action="{% url 'articles:comment' article.pk %}" class="d-flex align-items-center" method="POST">
      {% csrf_token %}
      <label for="comment">댓글 &nbsp;
      </label>
      <textarea maxlength="50" name="comment" id="comment" cols="100" rows="1" placeholder="여기에 댓글을 다세염"></textarea>
      <button type="submit">댓글달기</button>
    </form>
    <hr>
    <div class="d-flex justify-content-start">
      <form action="{% url 'articles:update' article.pk %}">
        <button>수정</button>
      </form>
      <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button>삭제</button>
      </form>
      <a href="{% url 'articles:index' %}">Back</a>
    </div>
  </footer>
  <!--modal-->
  <div class="modal fade" id="upcheck" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">추천?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          추천할래?
        </div>
        <div class="modal-footer">
          <form action="{% url 'articles:upcount' article.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">추천</button>
          </form>

          <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">시러</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

articles/templates/articles/pointshop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <hr>
  <h2 class="shopbox blaka">Icon Shop</h2>
  {% for icon in icons %}
    {% if icon.icon_id != 0 %}
      <button type="button" data-bs-toggle="modal" data-bs-target="#iconmodal{{ icon.icon_id }}" class="btn btn-outline-primary padzero ">
        <img style="width: 50px; height: 50px;" src="{% static icon.url %}" alt="icon"/></button>

      <div class="modal fade" id="iconmodal{{ icon.icon_id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="d-flex justify-content-end">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="justify-evenly">
              <div>
                <h5 class="modal-title" id="exampleModalLabel">
                  {{ icon.iconname }}
                  아이콘
                </h5>
              </div>
            </div>
            <hr>
            <div class="modal-body justify-evenly">
              <img style="width: 50px; height: 50px;" src="{% static icon.url %}" alt="icon"/>
              <div class="cutefont">가격 :
                {{ icon.price }}
                point
              </div>
            </div>
            <div class="modal-footer justify-space">
              <div>
                보유 :
                {{ user.point }}
                point
              </div>
              <div class="d-flex justify-content-end">
                {% if icon.icon_id in useritems %}
                  <button type="button" class="purchasebox" data-bs-dismiss="modal">이미보유중</button>
                {% elif user.point >= icon.price %}
                  <form action="{% url 'articles:icon_buy' icon.icon_id icon.price %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="purchasebox">구매하기</button>
                  </form>
                  <button type="button" class="purchasebox" data-bs-dismiss="modal">안살래</button>
                {% elif user.point < icon.price %}
                  <button type="button" class="purchasebox" data-bs-dismiss="modal">포인트부족ㅋ</button>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endif %}
  {% endfor %}
  <hr>
  <h2 class="shopbox blaka">Color Shop</h2>
  {% for col, price in color_list.items %}
    <button type="button" data-bs-toggle="modal" data-bs-target="#iconmodal{{ col }}" class="btn btn-outline-primary padzero ">
      <div class="colorbox" style="background-color: {{ col }};"></div>
    </button>

    <div class="modal fade" id="iconmodal{{ col }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="d-flex justify-content-end">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="justify-evenly">
            <div>
              <h5 class="modal-title" id="exampleModalLabel">
                <span style="color: {{ col }}; font-weight: bold;">{{ col }}</span>
              </h5>
            </div>
          </div>
          <hr>
          <div class="modal-body justify-evenly">
            <div class="colorbox" style="background-color: {{ col }};"></div>
            <div class="cutefont">가격 :
              {{ price }}
              point
            </div>
          </div>
          <div class="modal-footer justify-space">
            <div>
              보유 :
              {{ user.point }}
              point
            </div>
            <div class="d-flex justify-content-end">
              {% if col in usercolors %}
                <button type="button" class="purchasebox" data-bs-dismiss="modal">이미보유중</button>
              {% elif user.point >= price %}
                <form action="{% url 'articles:color_buy' col price %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="purchasebox">구매하기</button>
                </form>
                <button type="button" class="purchasebox" data-bs-dismiss="modal">안살래</button>
              {% elif user.point < price %}
                <button type="button" class="purchasebox" data-bs-dismiss="modal">포인트부족ㅋ</button>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  <hr>
  <a href="{% url 'articles:index' %}">돌아가기</a>

{% endblock content %}

articles/templates/articles/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Profile</h1>
  <hr>
  <h3 class="cutefont">보유 아이콘</h3>
  <div class="justify-start">
    {% for icon in iconlist %}
      <div style="margin: 5px;">
        <button type="button" data-bs-toggle="modal" data-bs-target="#iconsetting{{ icon.icon_id }}" class="btn btn-outline-primary padzero ">
          <img style="width: 50px; height: 50px;" src="{% static icon.url %}" alt="icon"/></button>
      </div>

      <div class="modal fade" id="iconsetting{{ icon.icon_id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="d-flex justify-content-end">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="justify-evenly">
              <div>
                <h5 class="modal-title" id="exampleModalLabel">
                  아이콘 장착할래?
                </h5>
              </div>
            </div>
            <hr>
            <div class="modal-body justify-evenly">
              <img style="width: 50px; height: 50px;" src="{% static icon.url %}" alt="icon"/>
            </div>
            <div class="modal-footer justify-space">
              <div class="d-flex justify-content-end">
                <form action="{% url 'articles:icon_setting' icon.icon_id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="purchasebox">그랭</button>
                </form>
                <button type="button" class="purchasebox" data-bs-dismiss="modal">시러</button>
              </div>
            </div>
          </div>
        </div>
      </div>

    {% endfor %}
  </div>
  <hr>
  <h3 class="cutefont">보유 칼라</h3>
  <div class="justify-start">
    {% for col in colorlist %}
      <div style="margin: 5px;">
        <button type="button" data-bs-toggle="modal" data-bs-target="#iconsetting{{ col.color }}" class="btn btn-outline-primary padzero ">
          <div class="colorbox" style="background-color: {{ col.color }};"></div>
        </button>
      </div>

      <div class="modal fade" id="iconsetting{{ col.color }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="d-flex justify-content-end">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="justify-evenly">
              <div>
                <h5 class="modal-title" id="exampleModalLabel">
                  <span style="color: {{ col.color }}; font-weight: bold;">{{ col.color }}
                  </span>세팅할래?
                </h5>
              </div>
            </div>
            <hr>
            <div class="modal-body justify-evenly">
              <div class="colorbox" style="background-color: {{ col.color }};"></div>
            </div>
            <div class="modal-footer justify-space">
              <div class="d-flex justify-content-end">
                <form action="{% url 'articles:color_username' col.color %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="purchasebox">아이디 색변경</button>
                </form>
                <form action="{% url 'articles:color_title' col.color %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="purchasebox">게시글 색변경</button>
                </form>
                <button type="button" class="purchasebox" data-bs-dismiss="modal">시러</button>
              </div>
            </div>
          </div>
        </div>
      </div>

    {% endfor %}
  </div>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>

  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정">
  </form>

  <a href="{% url 'articles:detail' article.pk %}">
    <button>뒤로가기</button>
  </a>

{% endblock content %}