accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='password'),
]

articles/urls.py
from django.http import JsonResponse
from django.urls import path
from . import views

app_name = 'articles'

def data1(request):
    data = {
        "name": "1",
        "level": 10,
        "url":"https://www.koreaminecraft.net/files/attach/images/21283/212/699/11167c822299f03f6f86ffd1ff4f5e3c.png",
        "item": ["검", "방패" ]
    }
    return JsonResponse(data)

def data2(request):
    data = {
        "name": "2",
        "level": 20,
        "url":"https://pixelart.pe.kr/data/editor/2109/afda73261b1d6e9b9d975acb9cedf366_1631624938_7116.png",
        "item": ["창", "검"]
    }
    return JsonResponse(data)

urlpatterns = [
    path('', views.index, name='index'),

    # Rest
    path('data1',data1),
    path('data2',data2),
    path('page',views.get_page),


    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment, name='comment'),
    path('<int:article_pk>/upcount', views.upcount, name='upcount'),
    path('search/', views.search, name='search'),
    path('pointshop/', views.pointshop, name='pointshop'),
    path('<int:icon_id>/<int:icon_price>/buy/', views.icon_buy, name='icon_buy'),
    path('profile/', views.profile, name='profile'),
    path('<int:icon_id>/icon_setting/', views.icon_setting, name='icon_setting'),
    path('<int:article_pk>/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:color_name>/<int:color_price>/buy/', views.color_buy, name='color_buy'),
    path('<str:color_name>/color_setting/username', views.color_username, name='color_username'),
    path('<str:color_name>/color_setting/title', views.color_title, name='color_title'),



    

    path('download/', views.download, name='download'),
    path('test/', views.test, name='test'),
    

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movies, name='movies'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>', views.detail, name='detail'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.connect),
    path('test/', views.test),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/movie_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    <title>사이트연습</title>

  </head>

  <body>
    
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light my-3" style="background-color: #e3f2fd;">
        <a class="navbar-brand disabled">
          <i class="fab fa-instagram ">
            <a href="{% url 'articles:index' %}"><img src="{% static 'img/ssafy.png' %}" width='100px;' style='margin-right: 10px;'></a>
          </i>
          <span class="insta">| SSAFYstagram</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <ul class="navbar-nav ms-3">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'articles:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:create' %}">NewPost</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:pointshop' %}">PointShop</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'articles:download' %}">PlayGround</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:movies' %}">Movies</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-3 align-items-center">
            <li class="nav-item">
              <a href="{% url 'articles:profile' %}" class="nav-link" style="color: purple;">
                <img style="width: 20px; height: 20px;" src="{% static profile.icon_url %}" alt="icon"/>
                {{ user }}
                {% if request.user.is_authenticated %}
                  // Point:
                  {{ user.point }}
                {% endif %}
              </a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <form class="nav-link" action="{% url 'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-outline-primary padzero">로그아웃</button>
                </form>
              </li>
              <li class="nav-item me-2">
                <a class="nav-link" href="{% url 'accounts:update' %}" style="padding: 0px; ">
                  <button type="button" class="btn btn-outline-primary padzero">회원정보수정</button>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="padding: 0px; ">
                  <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-outline-primary padzero ">회원탈퇴</button>
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}" style="padding: 4px; ">
                  <button type="button" class="btn btn-outline-primary padzero">로그인</button>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}" style="padding: 4px; ">
                  <button type="button" class="btn btn-outline-primary padzero">회원가입</button>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <div class="container">
        {% if request.user.is_authenticated %}
          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">ㅠㅠ</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  떠나지마세요 ㅠㅠ
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">남아있기</button>
                  <form action="{% url 'accounts:delete' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">냉정히 회원탈퇴</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        {% endif %}
        {% block content %}{% endblock content %}

      </div>
      {% comment %} <iframe style="position: fixed; top: 800px; left: 1600px;" controls="controls" src="{% static 'music/summer.mp3' %}" type="audio/mp3" loop="loop"></iframe> {% endcomment %}
      
      <script src="{% static 'js/app.js' %}"></script>
    </body>

  </html>

templates/ttest.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
      async function getData(id) {
        //response promise

        //XMLHTTPRequest 이게 원리가되는 코어 함수
        //이걸 이용해서 fetch를 만듬
        //요청 쉽게했는데
        //받아온거를 fetch는 뭘 더섞은거야
        //responsePromise.status() .aa .ff .bb. . ddd
        const responsePromise = await fetch('http://localhost:8000/articles/page?page=' + id);
        return responsePromise.json();
      }

      /////////////////////
      (async () => {
        const data = await getData(1);
        const data2 = await getData(2);
        console.log(data);
        console.log(data2);

        const bodyTag = document.querySelector('body')
        const divTag = document.createElement('div')
        bodyTag.append(divTag)
        //string만 보여주는거임.. 그래서 json은 안보이는..
        //json->string처럼 보여주려니까 [object Object]
        //그럼 안에껄 string처럼 풀어버리려면 JSON.stringify(data)
        //divTag.innerText = JSON.stringify(data)
        console.log(JSON.stringify(data))

        function getArticleElement(data) {
          const articleElement = document.createElement('div');
          articleElement.innerHTML = `
          <div class='article'>
            <div class='id'>1</div>
            <div class='content'>2</div>
          </div>
          `;

          articleElement
            .querySelector('.id')
            .innerText = data.fields.title;

          return articleElement;
        }

        data.forEach((datum) => {
          const element = getArticleElement(datum);
          document
            .querySelector('.articles')
            .append(element);
        })

      })();
    </script>
    <style>
      .article {
        display: flex;
        border: solid 1px black;
        border-bottom: none;
      }

      .article .id {
        color: blue;
        min-width: 50px;
      }

      .article .content {
        color: red;
      }
    </style>
  </head>

  <body>
    <div class='articles'>

      <!-- <div class='article'> <div class='id'>1</div> <div class='content'>2</div> </div> <div class='article'> <div class='id'>1</div> <div class='content'>2</div> </div> -->
    </div>
  </body>

</html>